name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip -o "DreiWeichen_v3.zip" -d .

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Generate Gradle Wrapper (8.7)
        run: gradle wrapper --gradle-version 8.7 --distribution-type all

      - name: Make wrapper executable
        run: chmod +x gradlew

      - name: Build Debug APK (with stacktrace)
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      # Hilft uns zu sehen, wo die APK liegt
      - name: List build outputs
        run: |
          echo "Tree under app/build:"
          find app/build -maxdepth 4 -type f -print || true

      # <-- Das ist der wichtige Teil, der vorher gefehlt hat
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: DreiWeichen-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Falls doch Fehler: Logs mitschicken
      - name: Save Gradle logs (if any)
        if: failure()
        run: |
          mkdir -p logs
          cp -r app/build/reports logs/ || true
          cp -r app/build/outputs/logs logs/ || true

      - name: Upload Gradle logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: logs
