name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: unzip -o "DreiWeichen_v2.zip" -d .

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Generate Gradle Wrapper (8.7)
        run: gradle wrapper --gradle-version 8.7 --distribution-type all

      - name: Make wrapper executable
        run: chmod +x gradlew

      - name: Build Debug APK (with stacktrace)
        run: ./gradlew assembleDebug --stacktrace || (cat app/build/reports/*/*.* || true; exit 1)

      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: app/build/reports
